### ISSUE TITLE
dec,(hl) throws internal error

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/pyz80#20]
While changing some code I accidentally ended up with ``dec,(iy+something)`` - note the additional rogue comma. Instead of throwing an error about an invalid instruction, I was given:

        [exec] pass  1 ...
        [exec] Traceback (most recent call last):
        [exec]   File "C:\Users\stefan\git\pyz80\pyz80.py", line 1969, in <module>
        [exec]     assembler_pass(p, inputfile)
        [exec]   File "C:\Users\stefan\git\pyz80\pyz80.py", line 1776, in assembler_pass
        [exec]     origin = (origin + bytes) % 65536
        [exec] TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

A simple ``dec,(hl)`` is sufficient to trigger this.

**Comment by stripwax** [comment]
Coibcidentally I encountered something v similar (totally human error, same
exception raised). In my case I was trying to assemble the following (note
again rogue comma)

djnz, -loop

**Comment by simonowen** [comment]
From the error I suspect it's a side-effect of pyz80 evaluating expressions in native Python. The comma will be seen as a separator for a tuple/list, which rightly gets rejected in arithmetic expressions.

I'll double-check that later, but would imagine a `try` block in the right place should be enough to catch this (and similar) evaluation failures.

**Comment by stefandrissen** [comment]
The worst part was that there is nothing to indicate which source code line is causing the error. I literally had to go through my source adding statements that did not compile to find the offender.

**Comment by simonowen** [comment]
Hopefully the latest code fixes both of your issues!
